# Generated by Django 3.1.6 on 2021-03-17 11:13

import api.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('market', models.CharField(choices=[('aFRR', 'aFRR'), ('mFRR', 'mFRR')], default='aFRR', max_length=4)),
                ('direction', models.CharField(choices=[('U', 'up'), ('D', 'down')], default='D', max_length=1)),
                ('tender_round', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('bid_file', models.FileField(upload_to=api.models.user_directory_path)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromdate', models.DateField()),
                ('todate', models.DateField()),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='api.tender')),
            ],
        ),
        migrations.CreateModel(
            name='BidRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('max_price_wkdy', models.IntegerField()),
                ('max_price_wknd', models.IntegerField()),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_rounds', to='api.tender')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('ours', models.BooleanField(default=False)),
                ('bid_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='api.bidround')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='api.unit')),
            ],
        ),
    ]
