# Generated by Django 3.1.6 on 2021-03-16 13:29

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='bid_file',
            field=models.FileField(upload_to=api.models.user_directory_path),
        ),
    ]
