# Generated by Django 3.1.6 on 2021-02-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210217_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='direction',
            field=models.CharField(choices=[('U', 'up'), ('D', 'down')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='tender',
            name='market',
            field=models.CharField(choices=[('aFRR', 'aFRR'), ('mFRR', 'mFRR')], default='aFRR', max_length=4),
        ),
    ]
