# Generated by Django 3.1.6 on 2021-02-25 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210218_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tender',
            options={'ordering': ['date']},
        ),
    ]
