# Generated by Django 3.1.6 on 2021-02-25 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210225_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tender',
            options={},
        ),
    ]
