name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run api unit tests
        run: docker-compose run test_api
      
      - name: Build and launch containers
        run: docker-compose up -d
